backend:
  name: git-gateway
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter-html"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
